{{ if eq .Values.dnsProvider "azure" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-dns-service-principal
  namespace: cert-manager
type: Opaque
stringData:
  client-secret: {{ .Values.clientSecret | quote }}
{{- end }}
