{{ if eq .Values.dnsProvider "local" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: incluster-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: InCluster Root CA
  secretName: incluster-root-ca
  duration: 43800h  # 5 Jahre
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
{{ end }}
