---
all:
  children:
    rke2_cluster:
      children:
        rke2_servers:
          hosts:
            rke2-server-01:
              ansible_host: 172.16.0.11
            # Add additional server nodes for HA (optional)
            rke2-server-02:
              ansible_host: 172.16.0.139
            rke2-server-03:
              ansible_host: 172.16.0.126
        rke2_agents:
          hosts:
            rke2-agent-01:
              ansible_host: 172.16.0.214
            rke2-agent-02:
              ansible_host: 172.16.0.8
            rke2-agent-03:
              ansible_host: 172.16.0.15
