---
apiVersion: v1
stringData:
  name: internal-admin-cluster
  password: {{ .Values.repository.token }}
  project: default
  type: git
  url: https://gitlab.procilon.de/cloud-and-infrastructure/admin-cluster/internal-admin-cluster.git
  username: token
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: internal-admin-cluster-repo
  namespace: argocd
type: Opaque
